on:
   push:
        branches:
        - master

  
  jobs :
    build:
      runs-on: ubuntu-latest

      steps:
       - uses : actions/checkout@vt

       - name : "login "

       run: docker login --username ${{secrets.DOCKER}} --password ${{secrets.DOCKER_TOKEN}}


