on:
   push:
        branches:
        - master

jobs :
  build:
      runs-on: ubuntu-latest

      steps:
        - uses : actions/checkout@v2

        - name : "login "

        run: docker login --username ${{secrets.DOCKER}} --password ${{secrets.DOCKER_TOKEN}}


